- name: Git checkout bitwarden
  ansible.builtin.git:
    repo: 'https://github.com/BenMcH/bitwarden_rs-docker-compose.git'
    dest: ~/bitwarden-docker
    force: true

- name: Replace .env
  template:
    src: templates/.env.j2
    dest: ~/bitwarden-docker/.env

- name: Untar bw_data
  unarchive:
    src: ./bw_data.tar.gz
    dest: ~/bitwarden-docker


- name: Create and start service
  community.docker.docker_compose:
    project_src: ~/bitwarden-docker
  register: output
